/**
 * A successfully parsed tool call requested by the LLM.
 */
export interface ValidToolCallRequest {
  type: 'valid';
  /** Unique call identifier generated by the LLM provider. */
  id: string;
  /** Name of the tool requested. */
  name: string;
  /** Parsed JSON arguments matching the tool schema. */
  arguments: Record<string, unknown>;
}

/**
 * A tool call whose arguments failed JSON parsing or syntax validation.
 * Preserves the raw string emitted by the LLM for context reflection.
 */
export interface MalformedToolCallRequest {
  type: 'malformed';
  /** Unique call identifier generated by the LLM provider. */
  id: string;
  /** Name of the tool requested. */
  name: string;
  /** The unparseable raw string emitted by the model. */
  rawArguments: string;
  /** Description of the parsing syntax error. */
  parseError: string;
}

/**
 * Discriminated union of tool invocations requested by the model.
 * Discriminant is the "type" property ('valid' | 'malformed').
 */
export type ToolCallRequest = ValidToolCallRequest | MalformedToolCallRequest;

export interface CreateValidToolCallRequestParams {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface CreateMalformedToolCallRequestParams {
  id: string;
  name: string;
  rawArguments: string;
  parseError: string;
}

/**
 * Factory for creating strongly-typed ToolCallRequest domain entities.
 */
export class ToolCallRequestFactory {
  private constructor() {}

  static createValid(params: CreateValidToolCallRequestParams): ValidToolCallRequest {
    return {
      type: 'valid',
      id: params.id,
      name: params.name,
      arguments: params.arguments,
    };
  }

  static createMalformed(params: CreateMalformedToolCallRequestParams): MalformedToolCallRequest {
    return {
      type: 'malformed',
      id: params.id,
      name: params.name,
      rawArguments: params.rawArguments,
      parseError: params.parseError,
    };
  }
}
