/**
 * A successfully parsed tool call requested by the LLM.
 */
export interface ValidToolCall {
  type: 'valid';
  /** Unique call identifier generated by the LLM provider. */
  id: string;
  /** Name of the tool requested. */
  name: string;
  /** Parsed JSON arguments matching the tool schema. */
  arguments: Record<string, unknown>;
}

/**
 * A tool call whose arguments failed JSON parsing or syntax validation.
 * Preserves the raw string emitted by the LLM for context reflection.
 */
export interface MalformedToolCall {
  type: 'malformed';
  /** Unique call identifier generated by the LLM provider. */
  id: string;
  /** Name of the tool requested. */
  name: string;
  /** The unparseable raw string emitted by the model. */
  rawArguments: string;
  /** Description of the parsing syntax error. */
  parseError: string;
}

/**
 * Discriminated union of tool invocations requested by the model.
 * Discriminant is the "type" property ('valid' | 'malformed').
 */
export type ToolCall = ValidToolCall | MalformedToolCall;
